CREATE DATABASE DWEcommerce
GO

USE DWEcommerce
GO

CREATE  TABLE CATEGORY(
	CATEGORY_ID INT PRIMARY KEY IDENTITY(1000,1),
	DESCRIPTION VARCHAR(100),
	AVAILABLE BIT DEFAULT 1,
	CREATED_AT DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE BRAND(
	BRAND_ID INT PRIMARY KEY IDENTITY(1000,1),
	DESCRIPTION VARCHAR(100),
	AVAILABLE BIT DEFAULT 1,
	CREATED_AT DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE PRODUCT (
	PRODUCT_ID INT PRIMARY KEY IDENTITY(1000,1),
	NAME VARCHAR(500),
	DESCRIPTION VARCHAR(500),
	BRAND_ID INT REFERENCES BRAND(BRAND_ID),
	CATEGORY_ID INT REFERENCES CATEGORY(CATEGORY_ID),
	PRICE DECIMAL(10,2) DEFAULT 0,
	STOCK INT,
	IMG_PATH VARCHAR(150),
	IMG_NAME VARCHAR(100),
	AVAILABLE BIT DEFAULT 1,
	CREATED_AT DATETIME DEFAULT GETDATE()
)
GO


CREATE TABLE CLIENT(
	CLIENT_ID INT PRIMARY KEY IDENTITY(1000,1),
	NAME VARCHAR(100),
	LASTNAME VARCHAR(100),
	EMAIL VARCHAR (100),
	PASSWORD VARCHAR(150),
	RESET_PSWD BIT DEFAULT 1,
	CREATED_AT DATETIME DEFAULT GETDATE()
)
GO


CREATE TABLE SHOPP_CART(
	CART_ID INT PRIMARY  KEY IDENTITY(1000,1),
	CLIENT_ID INT REFERENCES CLIENT(CLIENT_ID),
	PRODUCT_ID INT REFERENCES PRODUCT(PRODUCT_ID),
	ITEMS INT
)
GO

CREATE TABLE SALE(
	SALE_ID INT PRIMARY KEY IDENTITY(1000,1),
	CLIENT_ID INT REFERENCES CLIENT(CLIENT_ID),
	ITEMS INT,
	TOTAL DECIMAL(10,2),
	CONTACT VARCHAR(50),
	DISTRICT_ID VARCHAR(10),
	PHONE VARCHAR(50),
	ADDRESS VARCHAR(500),
	TRANS_ID VARCHAR(50),
	CREATED_AT DATETIME DEFAULT GETDATE()
)
GO


CREATE TABLE SALE_DETAIL(
	DETAIL_ID INT PRIMARY KEY IDENTITY(1000,1),
	SALE_ID INT REFERENCES SALE(SALE_ID),
	PRODUCT_ID INT REFERENCES PRODUCT(PRODUCT_ID),
	ITEMS INT,
	TOTAL DECIMAL(10,2)
)
GO


CREATE TABLE [USER](
	USER_ID INT PRIMARY KEY IDENTITY(1000,1),
	NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	PASSWORD VARCHAR(150),
	RESET_PSWD BIT DEFAULT 1,
	ACTIVE BIT DEFAULT 1,
	CREATED_AT DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE [STATE](
	STATE_ID VARCHAR(2) NOT NULL PRIMARY KEY,
	DESCRIPTION VARCHAR(45) NOT NULL,
)
GO

CREATE TABLE CITY(
	CITY_ID VARCHAR(4) NOT NULL PRIMARY KEY,
	DESCRIPTION VARCHAR(45),
	STATE_ID VARCHAR(2) REFERENCES STATE(STATE_ID),
)
GO


CREATE TABLE LOCALITY(
	LOCALITY_ID VARCHAR(6) NOT NULL PRIMARY KEY,
	DESCRIPTION VARCHAR(45) NOT NULL,
	CITY_ID VARCHAR(4) REFERENCES CITY(CITY_ID),
	STATE_ID VARCHAR(2) REFERENCES STATE(STATE_ID)
)
GO
